//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WfControlVentas.wcfControlVentas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfControlVentas.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InicioSesion", ReplyAction="http://tempuri.org/IService/InicioSesionResponse")]
        System.Data.DataSet InicioSesion(string nombreUsuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InicioSesion", ReplyAction="http://tempuri.org/IService/InicioSesionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InicioSesionAsync(string nombreUsuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarUsuario", ReplyAction="http://tempuri.org/IService/agregarUsuarioResponse")]
        System.Data.DataSet agregarUsuario(string nomUsuario, string nomReal, string clave, string tUsuario, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/agregarUsuario", ReplyAction="http://tempuri.org/IService/agregarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> agregarUsuarioAsync(string nomUsuario, string nomReal, string clave, string tUsuario, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IngresarFactura", ReplyAction="http://tempuri.org/IService/IngresarFacturaResponse")]
        System.Data.DataSet IngresarFactura(float monto, int cantidad, int id, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IngresarFactura", ReplyAction="http://tempuri.org/IService/IngresarFacturaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> IngresarFacturaAsync(float monto, int cantidad, int id, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarFactura", ReplyAction="http://tempuri.org/IService/ActualizarFacturaResponse")]
        System.Data.DataSet ActualizarFactura(int id, float monto, int cantidad, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarFactura", ReplyAction="http://tempuri.org/IService/ActualizarFacturaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ActualizarFacturaAsync(int id, float monto, int cantidad, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IngresarVenta", ReplyAction="http://tempuri.org/IService/IngresarVentaResponse")]
        System.Data.DataSet IngresarVenta(int cant, int cantVnta, float precio, string estado, int idproducto, int idFc, int idUser, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IngresarVenta", ReplyAction="http://tempuri.org/IService/IngresarVentaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> IngresarVentaAsync(int cant, int cantVnta, float precio, string estado, int idproducto, int idFc, int idUser, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarVenta", ReplyAction="http://tempuri.org/IService/ActualizarVentaResponse")]
        System.Data.DataSet ActualizarVenta(int id, int idproducto, int cantVnta, int cant, float precio, string estado, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarVenta", ReplyAction="http://tempuri.org/IService/ActualizarVentaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ActualizarVentaAsync(int id, int idproducto, int cantVnta, int cant, float precio, string estado, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IngresarProducto", ReplyAction="http://tempuri.org/IService/IngresarProductoResponse")]
        System.Data.DataSet IngresarProducto(int canPant, string estilo, string marca, string talla, float precioU, string estado, int idFac, int idUser, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IngresarProducto", ReplyAction="http://tempuri.org/IService/IngresarProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> IngresarProductoAsync(int canPant, string estilo, string marca, string talla, float precioU, string estado, int idFac, int idUser, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarProducto", ReplyAction="http://tempuri.org/IService/ActualizarProductoResponse")]
        System.Data.DataSet ActualizarProducto(int id, int canPant, string estilo, string marca, string talla, float precioU, string estado, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarProducto", ReplyAction="http://tempuri.org/IService/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ActualizarProductoAsync(int id, int canPant, string estilo, string marca, string talla, float precioU, string estado, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarProducto", ReplyAction="http://tempuri.org/IService/EliminarProductoResponse")]
        System.Data.DataSet EliminarProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarProducto", ReplyAction="http://tempuri.org/IService/EliminarProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> EliminarProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarVenta", ReplyAction="http://tempuri.org/IService/EliminarVentaResponse")]
        System.Data.DataSet EliminarVenta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarVenta", ReplyAction="http://tempuri.org/IService/EliminarVentaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> EliminarVentaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarFacturaDinamico", ReplyAction="http://tempuri.org/IService/mostrarFacturaDinamicoResponse")]
        System.Data.DataSet mostrarFacturaDinamico(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarFacturaDinamico", ReplyAction="http://tempuri.org/IService/mostrarFacturaDinamicoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarFacturaDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarFacturaEdit", ReplyAction="http://tempuri.org/IService/mostrarFacturaEditResponse")]
        System.Data.DataSet mostrarFacturaEdit(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarFacturaEdit", ReplyAction="http://tempuri.org/IService/mostrarFacturaEditResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarFacturaEditAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarProductoDinamico", ReplyAction="http://tempuri.org/IService/mostrarProductoDinamicoResponse")]
        System.Data.DataSet mostrarProductoDinamico(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarProductoDinamico", ReplyAction="http://tempuri.org/IService/mostrarProductoDinamicoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarProductoDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarProductoCRUD", ReplyAction="http://tempuri.org/IService/mostrarProductoCRUDResponse")]
        System.Data.DataSet mostrarProductoCRUD(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarProductoCRUD", ReplyAction="http://tempuri.org/IService/mostrarProductoCRUDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarProductoCRUDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarVentaDinamico", ReplyAction="http://tempuri.org/IService/mostrarVentaDinamicoResponse")]
        System.Data.DataSet mostrarVentaDinamico(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarVentaDinamico", ReplyAction="http://tempuri.org/IService/mostrarVentaDinamicoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarVentaDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarVentaCRUD", ReplyAction="http://tempuri.org/IService/mostrarVentaCRUDResponse")]
        System.Data.DataSet mostrarVentaCRUD(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarVentaCRUD", ReplyAction="http://tempuri.org/IService/mostrarVentaCRUDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarVentaCRUDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarHistorialDinamico", ReplyAction="http://tempuri.org/IService/mostrarHistorialDinamicoResponse")]
        System.Data.DataSet mostrarHistorialDinamico(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarHistorialDinamico", ReplyAction="http://tempuri.org/IService/mostrarHistorialDinamicoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarHistorialDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarUsuarios", ReplyAction="http://tempuri.org/IService/mostrarUsuariosResponse")]
        System.Data.DataSet mostrarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarUsuarios", ReplyAction="http://tempuri.org/IService/mostrarUsuariosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/buscadorFacturas", ReplyAction="http://tempuri.org/IService/buscadorFacturasResponse")]
        System.Data.DataSet buscadorFacturas(int num, float mon, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/buscadorFacturas", ReplyAction="http://tempuri.org/IService/buscadorFacturasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscadorFacturasAsync(int num, float mon, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/buscadorProductos", ReplyAction="http://tempuri.org/IService/buscadorProductosResponse")]
        System.Data.DataSet buscadorProductos(int num, string letra, float dec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/buscadorProductos", ReplyAction="http://tempuri.org/IService/buscadorProductosResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscadorProductosAsync(int num, string letra, float dec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/buscadorVentas", ReplyAction="http://tempuri.org/IService/buscadorVentasResponse")]
        System.Data.DataSet buscadorVentas(int num, float dec, string letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/buscadorVentas", ReplyAction="http://tempuri.org/IService/buscadorVentasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscadorVentasAsync(int num, float dec, string letra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarInversion", ReplyAction="http://tempuri.org/IService/mostrarInversionResponse")]
        System.Data.DataSet mostrarInversion(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarInversion", ReplyAction="http://tempuri.org/IService/mostrarInversionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarInversionAsync(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarGanancia", ReplyAction="http://tempuri.org/IService/mostrarGananciaResponse")]
        System.Data.DataSet mostrarGanancia(System.DateTime fchInicio, System.DateTime fchFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/mostrarGanancia", ReplyAction="http://tempuri.org/IService/mostrarGananciaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> mostrarGananciaAsync(System.DateTime fchInicio, System.DateTime fchFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WfControlVentas.wcfControlVentas.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WfControlVentas.wcfControlVentas.IService>, WfControlVentas.wcfControlVentas.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet InicioSesion(string nombreUsuario, string clave) {
            return base.Channel.InicioSesion(nombreUsuario, clave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InicioSesionAsync(string nombreUsuario, string clave) {
            return base.Channel.InicioSesionAsync(nombreUsuario, clave);
        }
        
        public System.Data.DataSet agregarUsuario(string nomUsuario, string nomReal, string clave, string tUsuario, string usuario) {
            return base.Channel.agregarUsuario(nomUsuario, nomReal, clave, tUsuario, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> agregarUsuarioAsync(string nomUsuario, string nomReal, string clave, string tUsuario, string usuario) {
            return base.Channel.agregarUsuarioAsync(nomUsuario, nomReal, clave, tUsuario, usuario);
        }
        
        public System.Data.DataSet IngresarFactura(float monto, int cantidad, int id, string usuario) {
            return base.Channel.IngresarFactura(monto, cantidad, id, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IngresarFacturaAsync(float monto, int cantidad, int id, string usuario) {
            return base.Channel.IngresarFacturaAsync(monto, cantidad, id, usuario);
        }
        
        public System.Data.DataSet ActualizarFactura(int id, float monto, int cantidad, string usuario) {
            return base.Channel.ActualizarFactura(id, monto, cantidad, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ActualizarFacturaAsync(int id, float monto, int cantidad, string usuario) {
            return base.Channel.ActualizarFacturaAsync(id, monto, cantidad, usuario);
        }
        
        public System.Data.DataSet IngresarVenta(int cant, int cantVnta, float precio, string estado, int idproducto, int idFc, int idUser, string usuario) {
            return base.Channel.IngresarVenta(cant, cantVnta, precio, estado, idproducto, idFc, idUser, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IngresarVentaAsync(int cant, int cantVnta, float precio, string estado, int idproducto, int idFc, int idUser, string usuario) {
            return base.Channel.IngresarVentaAsync(cant, cantVnta, precio, estado, idproducto, idFc, idUser, usuario);
        }
        
        public System.Data.DataSet ActualizarVenta(int id, int idproducto, int cantVnta, int cant, float precio, string estado, string usuario) {
            return base.Channel.ActualizarVenta(id, idproducto, cantVnta, cant, precio, estado, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ActualizarVentaAsync(int id, int idproducto, int cantVnta, int cant, float precio, string estado, string usuario) {
            return base.Channel.ActualizarVentaAsync(id, idproducto, cantVnta, cant, precio, estado, usuario);
        }
        
        public System.Data.DataSet IngresarProducto(int canPant, string estilo, string marca, string talla, float precioU, string estado, int idFac, int idUser, string usuario) {
            return base.Channel.IngresarProducto(canPant, estilo, marca, talla, precioU, estado, idFac, idUser, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IngresarProductoAsync(int canPant, string estilo, string marca, string talla, float precioU, string estado, int idFac, int idUser, string usuario) {
            return base.Channel.IngresarProductoAsync(canPant, estilo, marca, talla, precioU, estado, idFac, idUser, usuario);
        }
        
        public System.Data.DataSet ActualizarProducto(int id, int canPant, string estilo, string marca, string talla, float precioU, string estado, string usuario) {
            return base.Channel.ActualizarProducto(id, canPant, estilo, marca, talla, precioU, estado, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ActualizarProductoAsync(int id, int canPant, string estilo, string marca, string talla, float precioU, string estado, string usuario) {
            return base.Channel.ActualizarProductoAsync(id, canPant, estilo, marca, talla, precioU, estado, usuario);
        }
        
        public System.Data.DataSet EliminarProducto(int id) {
            return base.Channel.EliminarProducto(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EliminarProductoAsync(int id) {
            return base.Channel.EliminarProductoAsync(id);
        }
        
        public System.Data.DataSet EliminarVenta(int id) {
            return base.Channel.EliminarVenta(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EliminarVentaAsync(int id) {
            return base.Channel.EliminarVentaAsync(id);
        }
        
        public System.Data.DataSet mostrarFacturaDinamico(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarFacturaDinamico(fchInicio, fchFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarFacturaDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarFacturaDinamicoAsync(fchInicio, fchFinal);
        }
        
        public System.Data.DataSet mostrarFacturaEdit(int id) {
            return base.Channel.mostrarFacturaEdit(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarFacturaEditAsync(int id) {
            return base.Channel.mostrarFacturaEditAsync(id);
        }
        
        public System.Data.DataSet mostrarProductoDinamico(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarProductoDinamico(fchInicio, fchFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarProductoDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarProductoDinamicoAsync(fchInicio, fchFinal);
        }
        
        public System.Data.DataSet mostrarProductoCRUD(int id) {
            return base.Channel.mostrarProductoCRUD(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarProductoCRUDAsync(int id) {
            return base.Channel.mostrarProductoCRUDAsync(id);
        }
        
        public System.Data.DataSet mostrarVentaDinamico(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarVentaDinamico(fchInicio, fchFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarVentaDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarVentaDinamicoAsync(fchInicio, fchFinal);
        }
        
        public System.Data.DataSet mostrarVentaCRUD(int id) {
            return base.Channel.mostrarVentaCRUD(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarVentaCRUDAsync(int id) {
            return base.Channel.mostrarVentaCRUDAsync(id);
        }
        
        public System.Data.DataSet mostrarHistorialDinamico(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarHistorialDinamico(fchInicio, fchFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarHistorialDinamicoAsync(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarHistorialDinamicoAsync(fchInicio, fchFinal);
        }
        
        public System.Data.DataSet mostrarUsuarios() {
            return base.Channel.mostrarUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarUsuariosAsync() {
            return base.Channel.mostrarUsuariosAsync();
        }
        
        public System.Data.DataSet buscadorFacturas(int num, float mon, string usuario) {
            return base.Channel.buscadorFacturas(num, mon, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscadorFacturasAsync(int num, float mon, string usuario) {
            return base.Channel.buscadorFacturasAsync(num, mon, usuario);
        }
        
        public System.Data.DataSet buscadorProductos(int num, string letra, float dec) {
            return base.Channel.buscadorProductos(num, letra, dec);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscadorProductosAsync(int num, string letra, float dec) {
            return base.Channel.buscadorProductosAsync(num, letra, dec);
        }
        
        public System.Data.DataSet buscadorVentas(int num, float dec, string letra) {
            return base.Channel.buscadorVentas(num, dec, letra);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscadorVentasAsync(int num, float dec, string letra) {
            return base.Channel.buscadorVentasAsync(num, dec, letra);
        }
        
        public System.Data.DataSet mostrarInversion(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarInversion(fchInicio, fchFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarInversionAsync(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarInversionAsync(fchInicio, fchFinal);
        }
        
        public System.Data.DataSet mostrarGanancia(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarGanancia(fchInicio, fchFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mostrarGananciaAsync(System.DateTime fchInicio, System.DateTime fchFinal) {
            return base.Channel.mostrarGananciaAsync(fchInicio, fchFinal);
        }
    }
}
